import type { Metadata } from "next"
import AppThemeProvider from "./theme/theme"

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang="en">
            <body>
                <AppThemeProvider>{children}</AppThemeProvider>
            </body>
        </html>
    )
}
